# NumPy Tutorial

In [1]:
import numpy as np

In [2]:
# Creating NumPy Arrays
# create array using python list and tuple
mylistarr = np.array([1,2,3,4,5])

In [3]:
mytuplearr = np.array((2,4,32,4,51))

In [4]:
# Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
# 1D array
zeros_1d = np.zeros(4) 
one_1d = np.ones(5)
range_1d = np.arange(10)
lspace = np.linspace(1,4,8)
emp = np.empty(10)
emp_like = np.empty_like(zeros_1d)

In [5]:
# 2D array
zeros_2d = np.zeros((3,4)) 
one_2d = np.ones((5,2))
eye = np.eye(3)
eye_2d = np.eye(2,3)

# Tutorial NumPy Function & Attributes

In [6]:
# Tutorial (NumPy Functions & Attributes)
arr = np.arange(99)

In [7]:
# reshape (Convert into 2D array)
arr = arr.reshape(3,33)

In [8]:
# Check the size of the element
arr.size

99

In [9]:
# Check the shape (rows and columns of an array)
arr.shape

(3, 33)

In [10]:
# Convert array into orignal form
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [11]:
# Reshape is used to convert array in 2d or 3d form whereas ravel() is used to retain the orignal form of an array.

# NumPy AXIS (2d array)

In [12]:
# axis0 == rows and axis1 == columns

arr_2d = [[1,2,3],[4,5,6],[7,1,0]]
arr = np.array(arr_2d)

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [14]:
# Sum of axis 0 (rows)
arr.sum(axis=0)

array([12,  8,  9])

In [15]:
# Sum of axis 1 (columns)
arr.sum(axis=1)

array([ 6, 15,  8])

In [16]:
# np.T == Transpose (It means rows become column and column becomes row)
arr_t = arr.T

In [17]:
# To check the number of dimensions use ndim
arr.ndim

2

In [18]:
# To iterate over array use flat method
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [19]:
# Some Important Functions argmax() & argmin() give minimun and maximun element index.
one = np.array([242,12,43,567,1])

In [20]:
one.argmax()

3

In [21]:
one.argmin()

4

In [22]:
# argsort() is used to give details about how an element should written to be sorted
one.argsort()

array([4, 1, 2, 0, 3])

In [23]:
# Same functions with 2d array
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [24]:
arr.argmax(axis=0)

array([2, 1, 1])

# Basic Math Operation

In [25]:
arr_1 = np.array([1,2,3,45,99])
arr_2 = np.array([2,5,6,55,1])

In [26]:
# Addition of two array elements
arr_1 + arr_2

array([  3,   7,   9, 100, 100])

In [27]:
# Multiplication of both array elements
arr_1 * arr_2

array([   2,   10,   18, 2475,   99])

In [30]:
# Find sq root of an array element
np.sqrt(arr_1)

array([1.        , 1.41421356, 1.73205081, 6.70820393, 9.94987437])

In [31]:
# Some basic aggrigation functions in NumPy - np.sum(), np.min(), np.max()
one.sum()

865

In [35]:
# Find element in array
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [39]:
np.where(arr > 5)

(array([1, 2]), array([2, 0]))

In [42]:
# Count Non Zero Element
np.count_nonzero(arr)

8

# Check the size of array in bytes (NumPy uses 3.5 times less storage)

In [43]:
import sys

In [49]:
py_arr = [1,2,4,57,7,9]
np_arr = np.array([1,2,4,57,7,9])

In [50]:
# Size of python array in bytes
sys.getsizeof(1) * len(py_arr)

168

In [51]:
# Size of numpy array in bytes
np_arr.itemsize * np_arr.size

48